name: mnist
channels:
  - pytorch
  - conda-forge
dependencies:
  - autopep8=1.4.4
  - pip=22.2
  - python=3.10.4
  - pytorch=1.12.0
  - torchvision=0.13.0
  - pip:
      - dstack==0.0.7
      - hydra-core==1.2.0
      - pytorch-lightning==1.6.5
