name: mnist
channels:
  - pytorch
  - conda-forge
dependencies:
  - autopep8=1.4.4
  - pip=22.2
  - python=3.10.4
  - gcc
  - pytorch=1.13.0
  - torchvision=0.14.1
  - pip:
      - hydra-core==1.2.0
      - pytorch-lightning==1.6.5
      - torchmetrics==0.11.1
      - -e .
