name: mnist
channels:
  - pytorch
  - conda-forge
dependencies:
  - autopep8=1.4.4
  - pip=22.2
  - python=3.10.4
  - pytorch=2.0.0
  - torchvision
  - pip:
      - hydra-core==1.3.2
      - hydra-optuna-sweeper==1.2.0
      - pytorch-lightning==2.0.2
      - tensorboard==2.13.0
      - torchmetrics==0.11.4
      - -e .
